apiVersion: skaffold/v2beta8
kind: Config
profiles:
build:
  local:
    # Don't push to dockerhub
    push: false
    useBuildkit: true
  artifacts:
    - image: charlymarchiaro/scrapoxy-auth
      context: .
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"

deploy:
  statusCheckDeadlineSeconds: 6000
  kubectl:
    manifests:
      - k8s/dev/scrapoxy-deployment.yaml